apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: terraform-test-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
      You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
spec:
  entrypoint: terra
  templates:
  - name: terra
    inputs:
      artifacts:
      - name: provider
        path: /provider.tf
        http:
          url: https://kiddcorp-terraform.s3.amazonaws.com/provider.tf
    container:
      image: hashicorp/terraform:latest
      command: [terraform]
      args: ["init"]
